---
name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
env:
  MAKEFLAGS: --jobs=4
  LILYPOND_VERSION: 2.24.1
  # TODO Update TECTONIC_VERSION to 0.15.0 once OpenSSL 3.0 is in the Docker
  # image:
  TECTONIC_VERSION: 0.14.1
  VARIANTS_PDF: eogsized
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          build-args: LILYPOND_VERSION=${{ env.LILYPOND_VERSION }}
          tags: my-lilydock:${{ env.LILYPOND_VERSION }}
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: ${{ env.TECTONIC_VERSION }}
      - run: cp -f "$(command -v tectonic)" "${{ github.workspace }}/tectonic"
      - name: Build PDFs
        uses: addnab/docker-run-action@v3
        with:
          options: |
            --volume ${{ github.workspace }}:${{ github.workspace }}
            --workdir ${{ github.workspace }}
            --env MAKEFLAGS
            --env VARIANTS_PDF
          image: my-lilydock:${{ env.LILYPOND_VERSION }}
          run: |
            git config --global --add safe.directory '*' &&
            make --environment-overrides booklayout/toplevel.pdf SKIP_SPELLCHECK=1 TECTONIC=${{ github.workspace }}/tectonic
      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            PDF/*/*.pdf
            booklayout/toplevel.pdf
